language: python
sudo: false
services: docker
dist: trusty

before_script:
    - travis_retry timeout 120 docker pull christophpohl/reproducible
    - docker run -itd --name dock -v $(pwd):/repro christophpohl/reproducible

script:
    - docker exec dock bash -c "cd repro/example && doit"
    - docker exec dock bash -c "make html"

deploy:
    privder: pages
    skip_cleanup: true
    github_token: $TRAVIS_GH_PAGES_KEY
    local_dir: ".build/html/"
    on:
        branch: master
