sudo: false
dist: trusty

jobs:
    include:
        - stage: example
          services: docker
          script:
              - travis_retry timeout 120 docker pull fb77/reproducible
              - docker run -itd --name dock -v $(pwd):/repro fb77/reproducible
              - docker exec dock bash -c "cd repro/example && doit"

        - stage: website
          language: python
          python: 3.6
          script:
              - doit

          deploy:
              privder: pages
              skip_cleanup: true
              github_token: $TRAVIS_GH_PAGES_KEY
              local_dir: ".build/"
              on:
                  branch: master
